NUM_RX = 1
VIRT_ANT = 1
NUM_CHIRPS = 150
NUM_ADC_SAMPLES = 200
RANGE_RESOLUTION = 0.0335
DOPPLER_RESOLUTION = 0.020
NUM_FRAMES = 3000
SKIP_SIZE = 4
ANGLE_RES = 1
ANGLE_RANGE = 90
ANGLE_BINS = (ANGLE_RANGE * 2) // ANGLE_RES + 1
BINS_PROCESSED = 112
c = 3e8  # Speed of light (m/s)
sample_rate = 4000  # Rate at which the radar samples from ADC (ksps - kilosamples per second)
freq_slope = 70  # Frequency slope of the chirp (MHz/us)
adc_samples = 200  # Number of samples from a single chirp
start_freq = 77  # Starting frequency of the chirp (GHz)
idle_time = 7  # Time before starting next chirp (us)
ramp_end_time = 57  # Time after sending each chirp (us)
num_tx = 2  # Number of transmitters
